---
title: "EDA"
author: "Rio Yan"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: 
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)

knitr::opts_chunk$set(
  fig.width = 9,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


load data
```{r, message=FALSE, warning=FALSE}
student_df = read.table("./student-mat.csv", header = TRUE, sep = ";") %>%
  janitor::clean_names() %>%
  mutate(grade = round((g1+g2+g3)/3,2),
        letter_grade = case_when(grade >= 10 ~ "pass",
                                 grade < 10 ~ "fail")) %>%
  dplyr::select(-g1,-g2,-g3,-grade) %>%
  mutate_if(is.character, as.factor)

view(student_df)
```


```{r, message=FALSE, warning=FALSE}
skimr::skim(student_df)
```



## exploritory analysis

### summary table for categorical

```{r, message=FALSE, warning=FALSE}
library(gtsummary)

mat_categorical =
  student_df %>% 
  dplyr::select(-age, -medu, -fedu, -traveltime, -studytime, -failures, -famrel, -freetime, -goout, -dalc,-walc,-health,-absences)

mat_categorical %>% 
  tbl_summary()
```

### continuous variable plot

```{r, message=FALSE, warning=FALSE}
# df of predictors 

x_corr = student_df %>% 
  dplyr::select(-school, -sex, -address,-famsize, -pstatus, -mjob, -fjob, -reason, -guardian, -schoolsup, -famsup , -paid, -activities, -nursery, -higher, -internet, -romantic, -letter_grade, -absences)


x = student_df %>% 
  dplyr::select(absences)

# vector of response
y_corr = student_df$letter_grade

theme1 <- trellis.par.get()
theme1$plot.symbol$col <- rgb(.2, .4, .2, .5)
theme1$plot.symbol$pch <- 16
theme1$plot.line$col <- rgb(.8, .1, .1, 1)
theme1$plot.line$lwd <- 2
theme1$strip.background$col <- rgb(.0, .2, .6, .2)
trellis.par.set(theme1)
plot1 = featurePlot(x_corr, y_corr, plot = "boxplot", labels = c("","Y"),
            type = c("p"), layout = c(4, 3))
plot2 = featurePlot(x, y_corr, plot = "boxplot", labels = c("","Y"),
            type = c("p"), layout = c(1,1))

plot3 = featurePlot(dplyr::select_if(student_df, is.numeric),
                    y = y_corr,
                    scales = list(x =list(relation ="free"),
                                  y =list(relation ="free")),
                    plot = "density", pch = "|",
                    auto.key = list(columns = 2))
library(cowplot)
plot_grid(plot1, plot2)
plot3
```


### Correlation plot

```{r, message=FALSE, warning=FALSE}
library(ggcorrplot)

corr_df = 
  student_df %>% 
  select(age, medu, fedu, traveltime, studytime, failures, famrel, freetime, goout, dalc, walc, health, absences, letter_grade) 

# correlation plot with only continous var
model.matrix(~0+., data = corr_df) %>% 
  cor(use = "pairwise.complete.obs") %>% 
   ggcorrplot(show.diag = F, type="lower", 
             lab=TRUE, lab_size=2, 
             title = "Correlation of parameters of interest")

# correlation plot with all variables
model.matrix(~0+., data = student_df) %>% 
  cor(use = "pairwise.complete.obs") %>% 
   ggcorrplot(show.diag = F, type="lower", 
             lab=TRUE, lab_size=2, 
             title = "Correlation of parameters of interest")

```